version: '3.2'

services:
  web:
    build: .
    container_name: powtoon_web
    depends_on:
      - db
    volumes:
      - .:/powtoon
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
    command: >
      sh -c "
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py fill_powtoon_admin_group_permissions &&
        python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: postgres:10.1
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=powtoon

    ports:
      - "5432:5432"
    volumes:
      - ./provision:/docker-entrypoint-initdb.d
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

