# Generated by Django 2.1.5 on 2019-01-10 23:22

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


def create_admin_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(
        name='Powtoon admins'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Powtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('shared_with', models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_share', 'Can share any Powtoons'), ('can_see', 'Can see any Powtoons')),
            },
        ),
        migrations.RunPython(create_admin_group, migrations.RunPython.noop),
    ]
